sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

install:
  #  - export LATEST_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  #  - echo $LATEST_VERSION
  #  - export NODE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  #  - echo $NODE_VERSION
  - export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest-v10.x/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  - echo $NODE_VERSION

script:
# build from source
  - docker build -t node-alpine-build --build-arg NODE_VERSION=$NODE_VERSION alpine-build
  - export CID=$(docker create node-alpine-build)
  - mkdir -p alpine/usr/bin
  - docker cp $CID:/node-v$NODE_VERSION/out/Release/node alpine/usr/bin

# build from prebuild
#  - docker build -t node-alpine-prebuild --build-arg NODE_VERSION=$NODE_VERSION alpine-prebuild
#  - export CID=$(docker create node-alpine-prebuild)
#  - mkdir -p alpine/usr/bin
#  - docker cp $CID:/usr/bin/node alpine/usr/bin

  - export REPO=$TRAVIS_REPO_SLUG
  #  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export TAG=$NODE_VERSION
  - docker build -t $REPO:$TAG alpine

after_success:
  - docker images
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - docker push $REPO
