sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

#install:
  #  - export LATEST_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  #  - echo $LATEST_VERSION
  #  - export NODE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  #  - echo $NODE_VERSION

install:
  - |
    export REPO=$TRAVIS_REPO_SLUG
    export BRANCH=12
    export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest-v$BRANCH.x/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')

script:
# build from source
#  - docker build -t node-alpine-build --build-arg NODE_VERSION=$NODE_VERSION alpine-build
#  - export CID=$(docker create node-alpine-build)
#  - mkdir -p alpine/usr/bin
#  - docker cp $CID:/node-v$NODE_VERSION/out/Release/node alpine/usr/bin
  # build from prebuild
  #  - docker build -t node-alpine-prebuild --build-arg NODE_VERSION=$NODE_VERSION alpine-prebuild
  #  - export CID=$(docker create node-alpine-prebuild)
  #  - mkdir -p alpine/usr/bin
  #  - docker cp $CID:/usr/bin/node alpine/usr/bin
  #  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  #  - docker build -t $REPO: latest alpine
  - |
    echo "Current version: $REPO:$NODE_VERSION"
    docker pull $REPO:$NODE_VERSION || echo 'image not found'
    if [[ "$(docker images -q $REPO:$NODE_VERSION 2> /dev/null)" == "" ]]; then
      curl -X POST --header "Content-Type: application/json" -d "{}" https://circleci.com/api/v1.1/project/gh/$REPO/tree/$BRANCH?circle-token=907565f9d37e10a88dda4901e72ba88d372d1618
      docker build -t $REPO:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .
    fi
    docker tag $REPO:$NODE_VERSION $REPO:$BRANCH
    docker images
    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    docker push $REPO

#after_success:
#  - docker images
#  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#  - docker push $REPO
