sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - export LATEST_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
  - echo $LATEST_VERSION
  - export NODE_VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t node-alpine-build --build-arg NODE_VERSION=$NODE_VERSION alpine-build
  - export CID=$(docker create node-alpine-build)
  - mkdir -p alpine/usr/local/bin
  - docker cp $CID:/usr/local/bin/node alpine/usr/local/bin

after_success:
  - export REPO=$TRAVIS_REPO_SLUG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG debian
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

