version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/node

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Get Latest Node Version
          command: |
            apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
            export REPO=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            export BRANCH=8
            export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest-v$BRANCH.x/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
            echo "export REPO=$REPO" >> $BASH_ENV
            echo "export NODE_VERSION=$NODE_VERSION" >> $BASH_ENV
            echo "export BRANCH=$BRANCH" >> $BASH_ENV

      - run:
          name: Build application Docker image
          command: |
            source $BASH_ENV
            echo "Current version: $REPO:$NODE_VERSION"
            docker pull $REPO:$NODE_VERSION || echo 'image not found'
            if [[ "$(docker images -q $REPO:$NODE_VERSION 2> /dev/null)" == "" ]]; then
              docker build -t $REPO:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .
            fi
            docker tag $REPO:$NODE_VERSION $REPO:$BRANCH
            docker images
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $REPO
