version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/node

    branches:
      only:
        - master

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Get Latest Node Version
          command: |
            apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
            export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
            echo $NODE_VERSION
            echo ${NODE_VERSION}
            echo 'export NODE_VERSION='$NODE_VERSION
            echo 'export NODE_VERSION='$NODE_VERSION >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build application Docker image
          command: |
            source $BASH_ENV
            echo 'Build docker with ' $NODE_VERSION
            docker pull microbox/node:$NODE_VERSION
            if [[ "$(docker images -q microbox/node:$NODE_VERSION 2> /dev/null)" == "" ]]; then
              docker build -t microbox/node:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push microbox/node:$NODE_VERSION
            fi
